### PR TITLE
Attempt to fix pagination

### LINKED ISSUE #1502: Datasets: Pagination broken with new search interface
On current master the pagination does not work anymore: The indicator does react (1-25 => 26- 50 etc,) but the displayed datasets do not change.

### Steps to Reproduce
Hava test instance with sufficient datasets to trigger pagination.

### Extra Details

reverting f137de831a89dfd4a0902dfc520d8d74c382b357. (#1434) does fix pagination, so it seems to be linked to the new search interface.

### PR DESCRIPTION
**Pull request by Ingvord**
Resolves #1502

### CODE REVIEW

File: src/app/datasets/dashboard/dashboard.component.ts [hunk 1]
```diff
@@ -187,7 +185,7 @@ export class DashboardComponent implements OnInit, OnDestroy {
     this.updateColumnSubscription();
 
     this.subscriptions.push(
-      combineLatest([this.readyToFetch$, this.loggedIn$])
+      combineLatest([this.pagination$, this.readyToFetch$, this.loggedIn$])
         .pipe(
           map(([_, loggedIn]) => [loggedIn]),
```
Comment (Ingvord) [inline src/app/datasets/dashboard/dashboard.component.ts:190]: Apparently this line now introduces troubles, as anything but loggedIn is ignored.

@nitrosx , @bpedersen2 what is the purpose of this line? Can we safely remove it?

Thanks

Comment (Ingvord) [reply src/app/datasets/dashboard/dashboard.component.ts]: Ah, found it, never mind! Fixed in [2cb3d63](https://github.com/SciCatProject/frontend/pull/1503/commits/2cb3d63842242f019cb18b333e79cdab1bb34700)

**Comment by Ingvord** [comment]
All green :champagne:
